---

  - name: Deploy symfony-demo
    hosts: all
    user: www-data
    tasks:
      - name: Pull git repo
        git: repo=https://github.com/Samox/symfony-demo dest=/var/www/symfony-demo/current version=master

      - name: Run composer
        - shell: composer installation
          args:
            chdir: /var/www/symfony-demo/current
